/** @format */

import {
	sunglasses,
	cover,
	sunglasse,
	tote_bag,
	wool,
	wool2,
	wool3,
	woolblend,
	braided,
	khaki,
	leather_gloves,
	khaki_tote_bag,
	down_mittens,
	dock_sunglasses,
	tartan_scarf,
	tote_bag_2,
} from "./src/assets";

export const PRODUCT = [
	{
		id: 1,
		title: "Sunglass",
		desc: "These are timeless sunglasses that are designed in California and handmade in Japan by master craftsmen. The Brooks frames are made with a keyhole bridge, one of the many details the brand includes in their construction.",
		img: sunglasse,
		img2: dock_sunglasses,
		price: 80,
	},
	{
		id: 2,
		title: "Tote Bag",
		desc: "Meet your new favorite carry-on. Our supersized tote is crafted in durable waxed cotton canvas that's rugged and durable, ideal for hauling all of your stuff. This size takes you to and from the farmer's market, the gym or a weekend getaway.",
		img: tote_bag,
		img2: tote_bag_2,
		price: 50,
	},
	{
		id: 3,
		title: "Woolbend",
		desc: "his handsome belt will pull together any outfit. The strong materials will take on your wear patterns and look even better over time.",
		img: woolblend,
		img2: braided,
		price: 15,
	},
	{
		id: 4,
		title: "Wool",
		desc: "Crafted in the finest English wool from the Abraham Moon mill (established in 1837), this scarf is an elegant and cozy addition to your winter wardrobe.",
		img: wool,
		img2: tartan_scarf,
		price: 95,
	},
	{
		id: 5,
		title: "wool wrap",
		desc: "Our latest collection of handcrafted sunglasses features details like UV-protective lenses in shades specifically chosen to complement each frame, and all at a price that won't break the bank. We made these sunglasses with vintage-inspired acetate frames and a keyhole bridge.",
		img: wool2,
		img2: wool3,
		price: 65,
	},
	{
		id: 6,
		title: "Glass cove",
		desc: "These are timeless sunglasses that are designed in California and handmade in Japan by master craftsmen. The Brooks frames are made with a keyhole bridge, one of the many details the brand includes in their construction.",
		img: sunglasses,
		img2: cover,
		price: 85,
	},

	{
		id: 8,
		title: "khaki tote bag",
		desc: "These handsome leather belts are guaranteed to pull together any outfit. They're made of vegetable-tanned Italian leather, which means they have natural highs and lows of color and will look even better over time.",
		img: khaki,
		img2: khaki_tote_bag,
		price: 72,
	},
	{
		id: 9,
		title: "Leather Gloves",
		desc: "The smartest winter accessory. . . These 100 percent cashmere-lined gloves feature tech-friendly fingertips, so you can use your smartphone without getting frostbite.",
		img: leather_gloves,
		img2: down_mittens,
		price: 112,
	},
];
